/**
 * Swagger'dagi «Chat» bo'limining tepasida turadigan QO'LLANMA.
 *
 * Nega shu yerda?
 * Swagger (OpenAPI) faqat HTTP endpointlarini biladi — WebSocket hodisalarini
 * u ko'rsata olmaydi. Lekin Swagger UI **markdown**ni to'liq render qiladi:
 * sarlavha, jadval, ro'yxat va kod bloklari ishlaydi. Shundan foydalanamiz —
 * qo'llanmani teg tavsifiga joylaymiz, /docs ni ochgan bola darhol ko'radi.
 *
 * Matnni qator-qator yozib `join('\n')` qilamiz: shunda kod bloklarining
 * ``` belgilarini ekranlash (escape) kerak bo'lmaydi.
 */

export const CHAT_TAG = '6. Chat — jonli yozishuv (WebSocket)';

export const CHAT_GUIDE = [
  'Ikki taraf **jonli** yozishadigan oddiy chat: bir tarafda **mijoz**, ikkinchi tarafda **admin**.',
  '',
  'Bu bo‘lim — shunchaki endpointlar ro‘yxati emas, **qo‘llanma**. Pastda backendning',
  'har bir qismiga qanday frontend yozilishi qadamma-qadam ko‘rsatilgan. Kodni nusxa',
  'olib ishlatsangiz — chat ishlaydi.',
  '',
  '> **Tayyor namuna:** [/chat.html](/chat.html) — mijoz sahifasi. Uni brauzerda oching,',
  '> admin panelning «Chat» bo‘limi bilan yonma-yon qo‘ying va yozishib ko‘ring.',
  '> Sahifaning butun kodi bitta faylda, izohlari o‘zbekcha: `public/chat.html`.',
  '',
  '---',
  '',
  '## 1. Nega chat REST emas?',
  '',
  'Pastda faqat **5 ta HTTP endpoint** ko‘rasiz. Yozishuvning o‘zi HTTP orqali emas,',
  '**WebSocket** orqali ishlaydi.',
  '',
  '| | HTTP (REST) | WebSocket |',
  '|---|---|---|',
  '| Ulanish | so‘rov ketdi — javob keldi — **uzildi** | bir marta ulanadi va **ochiq turadi** |',
  '| Kim gapiradi | doim mijoz so‘raydi | **ikkala taraf ham** yubora oladi |',
  '| Manzil | `POST /api/products` | manzil yo‘q, **hodisa nomi** bor: `chat:message` |',
  '| Swagger | ko‘rsatadi | **ko‘rsata olmaydi** |',
  '',
  'Chatda server ham o‘zi xabar yubora olishi kerak: admin javob yozganda mijoz',
  'sahifasi **yangilanmasdan** ko‘rsin. REST buni qila olmaydi — u faqat',
  '«so‘rasang beraman» tarzida ishlaydi.',
  '',
  'Swagger OpenAPI standartiga asoslangan, u esa faqat HTTP haqida. Shu sababli',
  'hodisalar ro‘yxatini biz **qo‘lda** yozib qo‘ydik: **GET /api/chat/events** —',
  'uni ham xuddi shu sahifadan sinab ko‘rsangiz bo‘ladi.',
  '',
  '---',
  '',
  '## 2. Ulanish manzili va kutubxona',
  '',
  '```',
  'http://localhost:3000/chat            (lokalda)',
  'https://backend.magnateshop.uz/chat   (serverda)',
  '```',
  '',
  'Kutubxonani hech qayerdan yuklab olish shart emas — **backendning o‘zi tarqatadi**:',
  '',
  '```html',
  '<script src="/socket.io/socket.io.js"></script>',
  '```',
  '',
  'React/Vue loyihada esa paket sifatida:',
  '',
  '```bash',
  'npm install socket.io-client',
  '```',
  '',
  '---',
  '',
  '## 3. ⭐ Backendning qaysi qismiga qanday frontend yoziladi',
  '',
  'Eng muhim jadval. Chapda — backendda nima bor, o‘ngda — siz nima yozasiz.',
  '',
  '| Backendda | Frontendda yoziladigan kod | Qachon |',
  '|---|---|---|',
  '| `POST /api/chat/start` | `fetch(...)` yoki `axios.post(...)` | sahifa ochilganda, bir marta |',
  '| WebSocket gateway | `io(url)` | start’dan keyin, bir marta |',
  '| `chat:ready` (server yuboradi) | `socket.on(\'chat:ready\', ...)` | ulanish tayyor bo‘lganda |',
  '| `chat:join` (siz yuborasiz) | `socket.emit(\'chat:join\', {...})` | `chat:ready` ichida |',
  '| `chat:history` (server yuboradi) | `socket.on(\'chat:history\', ...)` | eski xabarlarni chizish |',
  '| `chat:message` (siz yuborasiz) | `socket.emit(\'chat:message\', {...})` | forma submit bo‘lganda |',
  '| `chat:message` (server yuboradi) | `socket.on(\'chat:message\', ...)` | yangi xabarni chizish |',
  '| `chat:typing` | `emit` — input’da, `on` — ko‘rsatishda | yozayotganda |',
  '| `chat:error` | `socket.on(\'chat:error\', ...)` | xatoni ko‘rsatish |',
  '| `GET /api/chat/chats` | `axios.get(...)` | admin panel ochilganda |',
  '| `chat:chats` (server yuboradi) | `socket.on(\'chat:chats\', ...)` | ro‘yxatni yangilash |',
  '',
  '**Qoida:** har `emit` uchun kimdadir `on` bo‘lishi kerak. Aks holda xabar',
  'jo‘natiladi-yu, hech kim eshitmaydi.',
  '',
  '---',
  '',
  '## 4. Mijoz tomoni — 5 qadam',
  '',
  '### 1-qadam. Suhbat ochish (oddiy HTTP)',
  '',
  'WebSocket’ga ulanishdan **oldin** shu chaqiriladi — chunki `chat:join` uchun',
  '`chatId` va `guestKey` kerak.',
  '',
  '```js',
  "const res = await fetch('/api/chat/start', {",
  "  method: 'POST',",
  "  headers: { 'Content-Type': 'application/json' },",
  '  body: JSON.stringify({',
  "    name: 'Aziz',",
  '    // Kalit bo‘lsa yuboramiz — shunda ESKI suhbat qaytadi',
  "    guestKey: localStorage.getItem('chat-key') || undefined,",
  '  }),',
  '});',
  '',
  'const body = await res.json();',
  'if (!body.success) throw new Error(body.message);   // xatolik matni o‘zbekcha',
  '',
  'const chat = body.data;                             // { id, guestKey, guestName }',
  "localStorage.setItem('chat-key', chat.guestKey);    // ⚠️ saqlash SHART",
  '```',
  '',
  '### 2-qadam. Ulanish',
  '',
  '```js',
  "const socket = io('/chat');",
  '// boshqa domenda bo‘lsa:',
  "// const socket = io('https://backend.magnateshop.uz/chat');",
  '```',
  '',
  '### 3-qadam. Suhbatga qo‘shilish',
  '',
  '`chat:ready` kelmasdan turib `chat:join` yubormang — server hali sizni',
  'tanib ulgurmagan bo‘ladi.',
  '',
  '```js',
  "socket.on('chat:ready', () => {",
  "  socket.emit('chat:join', { chatId: chat.id, guestKey: chat.guestKey });",
  '});',
  '```',
  '',
  '### 4-qadam. Eski yozishmalarni chizish',
  '',
  '```js',
  "socket.on('chat:history', (payload) => {",
  "  document.getElementById('messages').innerHTML = '';",
  '  payload.messages.forEach(showMessage);',
  '});',
  '```',
  '',
  '### 5-qadam. Yozish va o‘qish',
  '',
  '```js',
  '// yuborish',
  "form.addEventListener('submit', (e) => {",
  '  e.preventDefault();',
  "  socket.emit('chat:message', { chatId: chat.id, text: input.value });",
  "  input.value = '';",
  '});',
  '',
  '// ⚠️ O‘zingiz yuborgan xabar ham SHU YERGA qaytadi.',
  '// Shuning uchun yuborayotganda ekranga qo‘lda qo‘shmang — ikki marta chiqadi.',
  "socket.on('chat:message', showMessage);",
  '',
  '// xatolik — matni o‘zbekcha, o‘zgartirmasdan ko‘rsatsangiz bo‘ladi',
  "socket.on('chat:error', (e) => alert(e.message));",
  '```',
  '',
  '**Xabarni chizishda:**',
  '',
  '```js',
  'function showMessage(m) {',
  "  const el = document.createElement('div');",
  "  el.className = m.sender === 'guest' ? 'msg mine' : 'msg';",
  '  el.textContent = m.text;   // ⚠️ innerHTML EMAS — aks holda XSS bo‘ladi',
  '  messages.appendChild(el);',
  '}',
  '```',
  '',
  'Tamom. Chat ishlaydi.',
  '',
  '---',
  '',
  '## 5. Admin tomoni — bitta farq bor',
  '',
  'Admin **token** bilan ulanadi. Token bo‘lsa server sizni `admin` deb taniydi:',
  'barcha suhbatlar ro‘yxatini yuborib turadi va `guestKey` so‘ramaydi.',
  '',
  '```js',
  "const socket = io('/chat', {",
  '  // login qilib olingan accessToken',
  "  auth: { token: localStorage.getItem('admin-token') },",
  '});',
  '',
  "socket.on('chat:ready', (p) => console.log(p.role));   // 'admin'",
  '',
  '// Yangi mijoz kelganda yoki yangi xabar bo‘lganda O‘ZI keladi.',
  '// Ya‘ni har soniyada so‘rov yuborish (polling) KERAK EMAS.',
  "socket.on('chat:chats', (p) => renderChatList(p.chats));",
  '',
  '// Suhbatni ochish — adminga guestKey kerak emas',
  "socket.emit('chat:join', { chatId: 1 });",
  "socket.emit('chat:message', { chatId: 1, text: 'Ha, sotuvda bor' });",
  '```',
  '',
  'Token yubormasangiz — server sizni oddiy mijoz deb hisoblaydi va',
  'boshqalarning suhbatiga qo‘sha olmaysiz.',
  '',
  '---',
  '',
  '## 6. ⭐ React’da yozish (3 ta tuzoq bor)',
  '',
  'Admin panel React’da yozilgan. Sof JS’dan farqli uchta joyga e’tibor bering.',
  '',
  '### 1-tuzoq: ulanish har renderda takrorlanadi',
  '',
  'Yechim — `useEffect(..., [])` va **majburiy tozalash**:',
  '',
  '```jsx',
  'const socketRef = useRef(null);',
  '',
  'useEffect(() => {',
  "  const socket = io(WS_URL, { auth: { token } });",
  '  socketRef.current = socket;',
  '',
  "  socket.on('chat:history', (p) => setMessages(p.messages));",
  "  socket.on('chat:message', (m) => setMessages((list) => [...list, m]));",
  '',
  '  // ⚠️ Busiz: har renderda yangi ulanish qo‘shilib, xabar 2-3 marta ko‘rinadi',
  '  return () => socket.close();',
  '}, []);',
  '```',
  '',
  '### 2-tuzoq: `socket.on` ichida state ESKI qiymatda qotib qoladi',
  '',
  '`socket.on(...)` bir marta yoziladi. Uning ichidagi `activeId` o‘sha paytdagi',
  'qiymatda qolib ketadi (buni **stale closure** deyishadi). Yechim — `useRef`:',
  '',
  '```jsx',
  'const activeIdRef = useRef(null);',
  '',
  'const openChat = (id) => {',
  '  activeIdRef.current = id;    // ref — hodisa ichida o‘qish uchun',
  '  setActiveId(id);             // state — ekranga chizish uchun',
  "  socketRef.current.emit('chat:join', { chatId: id });",
  '};',
  '',
  "socket.on('chat:message', (m) => {",
  '  if (m.chatId !== activeIdRef.current) return;   // boshqa suhbatning xabari',
  '  setMessages((list) => [...list, m]);',
  '});',
  '```',
  '',
  '### 3-tuzoq: state’ni to‘g‘ridan-to‘g‘ri o‘zgartirish',
  '',
  '```jsx',
  'setMessages((list) => [...list, m]);   // ✅ yangi massiv',
  '// list.push(m); setMessages(list);    // ❌ React o‘zgarishni sezmaydi',
  '```',
  '',
  '**Bonus:** react-query ishlatsangiz, ro‘yxatni WebSocket’dan to‘g‘ridan-to‘g‘ri',
  'yangilash mumkin — qayta so‘rov yubormasdan:',
  '',
  '```jsx',
  "socket.on('chat:chats', (p) => queryClient.setQueryData(['chat','chats'], p.chats));",
  '```',
  '',
  '---',
  '',
  '## 7. Hodisalar (qisqacha)',
  '',
  '| Hodisa | Yo‘nalish | Ichida nima | Vazifasi |',
  '|---|---|---|---|',
  '| `chat:join` | yuborasiz | `{ chatId, guestKey? }` | suhbatga qo‘shilish |',
  '| `chat:message` | yuborasiz | `{ chatId, text }` | xabar yuborish |',
  '| `chat:typing` | yuborasiz | `{ chatId, isTyping }` | «yozmoqda…» |',
  '| `chat:read` | yuborasiz | `{ chatId }` | admin o‘qidi |',
  '| `chat:ready` | keladi | `{ role }` | ulanish tayyor |',
  '| `chat:history` | keladi | `{ chatId, messages }` | eski yozishmalar |',
  '| `chat:message` | keladi | xabar obyekti | yangi xabar |',
  '| `chat:typing` | keladi | `{ chatId, from, isTyping }` | qarshi taraf yozmoqda |',
  '| `chat:chats` | keladi | `{ chats }` | suhbatlar ro‘yxati (admin) |',
  '| `chat:error` | keladi | `{ message }` | xatolik sababi |',
  '',
  'To‘liq tavsifi va namunaviy ma’lumotlari bilan: **GET /api/chat/events**',
  '',
  '---',
  '',
  '## 8. Ko‘p uchraydigan xatolar',
  '',
  '| Nima bo‘ldi | Sababi | Yechim |',
  '|---|---|---|',
  '| «Avval suhbatga qo‘shiling» | `chat:join` qilmasdan xabar yuborildi | `chat:ready` ni kuting, keyin `chat:join` |',
  '| «Bu suhbat sizniki emas» | `guestKey` yuborilmadi yoki boshqa suhbatniki | `POST /api/chat/start` javobidagi `guestKey` ni yuboring |',
  '| «chatId butun son bo‘lishi kerak» | `chatId` matn ko‘rinishida yuborildi | `Number(chatId)` qiling |',
  '| Xabar ikki marta ko‘rinyapti | yuborayotganda ekranga qo‘lda ham qo‘shilgan | faqat `socket.on(\'chat:message\')` da chizing |',
  '| Xabar 2-3 marta ko‘rinyapti | React’da ulanish takrorlangan | `useEffect` tozalashida `socket.close()` |',
  '| Ulanish uzilib-ulanib turibdi | nginx WebSocket’ni o‘tkazmayapti | nginx’ga `Upgrade` / `Connection` sarlavhalari (DEPLOYMENT.md) |',
  '| Token yubordim, baribir `guest` | token `auth` emas, `query` da yuborilgan | `io(url, { auth: { token } })` |',
  '',
  '---',
  '',
  '## 9. O‘zingizni tekshiring',
  '',
  'Chat ishlagach, shu topshiriqlarni bajaring — hammasi mavjud hodisalar bilan hal bo‘ladi:',
  '',
  '1. Mijoz sahifasida «operator yozmoqda…» ni chiqaring (`chat:typing`)',
  '2. Admin panelda o‘qilmagan xabarlar sonini ko‘rsating (`unreadForAdmin` + `chat:read`)',
  '3. Xabar yuborilganda tovush chiqaring (`chat:message` ichida `new Audio(...).play()`)',
  '4. Aloqa uzilganda qizil chiziq ko‘rsating (`socket.on(\'disconnect\')`)',
  '5. Xabarni 1000 belgidan uzun qilib yuborib ko‘ring — server nima deydi?',
  '',
  '---',
  '',
  'Batafsil qo‘llanma va butun kod: repodagi **WEBSOCKET.md**',
].join('\n');
