/**
 * Namuna ma'lumotlar — 100 ta real avtomobil.
 *
 * Rasmlar `public/images/cars/` papkasida saqlanadi va server o'zi tarqatadi.
 * To'liq havola seed paytida quriladi: `${APP_URL}/images/cars/<image>`
 */

export interface SeedCategory {
  name: string;
  description: string;
}

export interface SeedCar {
  name: string;
  description: string;
  price: number;
  stock: number;
  /** public/images/cars/ ichidagi fayl nomi */
  image: string;
  category: string;
}

export const SEED_CATEGORIES: SeedCategory[] = [
  { name: 'Sedan', description: 'Kundalik yurish uchun qulay, tejamkor va keng bagajli avtomobillar' },
  { name: 'Krossover va SUV', description: 'Baland klirens, to‘liq g‘ildirak uzatmasi, oila va sayohat uchun' },
  { name: 'Xetchbek', description: 'Ixcham, shahar sharoitida parkovka qilish oson avtomobillar' },
  { name: 'Elektromobil', description: 'Benzinsiz, sokin va tejamkor — kelajak transporti' },
  { name: 'Sport avtomobil', description: 'Yuqori quvvat, tez tezlanish va sport dizayn' },
  { name: 'Lyuks va premium', description: 'Eng yuqori komfort, sifatli materiallar va boy jihozlar' },
  { name: 'Minivan', description: 'Ko‘p o‘rinli, katta oila va biznes tashish uchun' },
  { name: 'Pikap va yuk', description: 'Ochiq kuzov, yuk tashish va og‘ir ish sharoitlari uchun' },
];

export const SEED_CARS: SeedCar[] = [
  // ── Sedan ───────────────────────────────────────────────────
  {
    name: 'Toyota Camry 2.5 Hybrid',
    description: '2.5 L gibrid, 100 km ga 4.5 litr sarf',
    price: 545000000,
    stock: 7,
    image: 'toyota-camry-2-5-hybrid.jpg',
    category: 'Sedan',
  },
  {
    name: 'Volkswagen Passat 2.0 TSI',
    description: '2.0 L TSI, nemis sifati',
    price: 445000000,
    stock: 3,
    image: 'volkswagen-passat-2-0-tsi.jpg',
    category: 'Sedan',
  },
  {
    name: 'Honda Accord 1.5 Turbo',
    description: '1.5 L turbo, keng salon, yuqori komfort',
    price: 430000000,
    stock: 4,
    image: 'honda-accord-1-5-turbo.jpg',
    category: 'Sedan',
  },
  {
    name: 'Chevrolet Malibu 2.0 Turbo',
    description: '2.0 L turbo, 250 ot kuchi, biznes-klass sedan',
    price: 415000000,
    stock: 6,
    image: 'chevrolet-malibu-2-0-turbo.jpg',
    category: 'Sedan',
  },
  {
    name: 'Mazda 6 2.5',
    description: 'SkyActiv texnologiyasi, premium salon',
    price: 395000000,
    stock: 4,
    image: 'mazda-6-2-5.jpg',
    category: 'Sedan',
  },
  {
    name: 'Hyundai Sonata 2.5',
    description: '2.5 L benzin, zamonaviy dizayn',
    price: 385000000,
    stock: 6,
    image: 'hyundai-sonata-2-5.jpg',
    category: 'Sedan',
  },
  {
    name: 'Kia K5 2.0',
    description: '2.0 L, sport-sedan dizayni',
    price: 375000000,
    stock: 5,
    image: 'kia-k5-2-0.jpg',
    category: 'Sedan',
  },
  {
    name: 'Honda Civic 2.0',
    description: 'Sport ko‘rinish, tejamkor dvigatel',
    price: 355000000,
    stock: 5,
    image: 'honda-civic-2-0.jpg',
    category: 'Sedan',
  },
  {
    name: 'Nissan Altima 2.5',
    description: '2.5 L, CVT uzatmalar qutisi',
    price: 340000000,
    stock: 3,
    image: 'nissan-altima-2-5.jpg',
    category: 'Sedan',
  },
  {
    name: 'Skoda Octavia 1.8 TSI',
    description: 'Katta bagaj, nemis platformasi',
    price: 330000000,
    stock: 4,
    image: 'skoda-octavia-1-8-tsi.jpg',
    category: 'Sedan',
  },
  {
    name: 'Toyota Corolla 1.8',
    description: 'Dunyodagi eng ko‘p sotilgan avtomobil',
    price: 320000000,
    stock: 9,
    image: 'toyota-corolla-1-8.jpg',
    category: 'Sedan',
  },
  {
    name: 'Volkswagen Jetta 1.4 TSI',
    description: '1.4 L turbo, tejamkor va dinamik',
    price: 315000000,
    stock: 5,
    image: 'volkswagen-jetta-1-4-tsi.jpg',
    category: 'Sedan',
  },
  {
    name: 'Hyundai Elantra 1.6',
    description: '1.6 L benzin, yoshlar uchun ideal',
    price: 285000000,
    stock: 8,
    image: 'hyundai-elantra-1-6.jpg',
    category: 'Sedan',
  },
  {
    name: 'Kia Cerato 1.6',
    description: '1.6 L, ishonchli oilaviy sedan',
    price: 265000000,
    stock: 7,
    image: 'kia-cerato-1-6.jpg',
    category: 'Sedan',
  },
  {
    name: 'Chevrolet Cobalt 1.5 MT',
    description: '1.5 L benzin, mexanika, eng ommabop byudjet sedan',
    price: 165000000,
    stock: 24,
    image: 'chevrolet-cobalt-1-5-mt.jpg',
    category: 'Sedan',
  },
  {
    name: 'Chevrolet Lacetti 1.6',
    description: '1.6 L benzin, ishonchli va arzon xizmat ko‘rsatish',
    price: 148000000,
    stock: 11,
    image: 'chevrolet-lacetti-1-6.jpg',
    category: 'Sedan',
  },
  {
    name: 'Daewoo Nexia 3',
    description: '1.5 L benzin, oddiy va tejamkor',
    price: 112000000,
    stock: 15,
    image: 'daewoo-nexia-3.jpg',
    category: 'Sedan',
  },
  // ── Krossover va SUV ────────────────────────────────────────
  {
    name: 'Toyota Land Cruiser 300',
    description: '3.5 V6 Twin-Turbo, afsonaviy ramali SUV',
    price: 1450000000,
    stock: 2,
    image: 'toyota-land-cruiser-300.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Nissan Patrol 5.6 V8',
    description: '5.6 L V8, cho‘l va tog‘ uchun',
    price: 1250000000,
    stock: 1,
    image: 'nissan-patrol-5-6-v8.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Chevrolet Tahoe 5.3 V8',
    description: '5.3 L V8, to‘laqonli katta SUV',
    price: 1150000000,
    stock: 2,
    image: 'chevrolet-tahoe-5-3-v8.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Toyota Land Cruiser Prado',
    description: 'Yo‘lsizlik uchun ideal, ishonchli',
    price: 950000000,
    stock: 3,
    image: 'toyota-land-cruiser-prado.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Jeep Grand Cherokee 3.6',
    description: 'Amerika SUV klassikasi',
    price: 880000000,
    stock: 2,
    image: 'jeep-grand-cherokee-3-6.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Toyota Highlander 3.5 V6',
    description: '7 o‘rinli premium krossover',
    price: 780000000,
    stock: 3,
    image: 'toyota-highlander-3-5-v6.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Hyundai Palisade 3.8 V6',
    description: 'Katta oilaviy SUV, lyuks salon',
    price: 750000000,
    stock: 2,
    image: 'hyundai-palisade-3-8-v6.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Honda Pilot 3.5 V6',
    description: '8 o‘rinli oilaviy SUV',
    price: 690000000,
    stock: 2,
    image: 'honda-pilot-3-5-v6.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Kia Sorento 2.5',
    description: '7 o‘rin, kuchli dvigatel',
    price: 565000000,
    stock: 3,
    image: 'kia-sorento-2-5.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Hyundai Santa Fe 2.5',
    description: '7 o‘rinli, premium daraja',
    price: 545000000,
    stock: 4,
    image: 'hyundai-santa-fe-2-5.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Toyota RAV4 2.5 Hybrid',
    description: 'Gibrid, AWD, tejamkor krossover',
    price: 520000000,
    stock: 8,
    image: 'toyota-rav4-2-5-hybrid.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Honda CR-V 1.5 Turbo',
    description: '1.5 L turbo, keng bagaj',
    price: 465000000,
    stock: 6,
    image: 'honda-cr-v-1-5-turbo.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Mazda CX-5 2.5 AWD',
    description: 'SkyActiv, premium ichki bezak',
    price: 455000000,
    stock: 5,
    image: 'mazda-cx-5-2-5-awd.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Nissan X-Trail 2.5 AWD',
    description: 'To‘liq uzatma, qulay yurish',
    price: 445000000,
    stock: 4,
    image: 'nissan-x-trail-2-5-awd.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Kia Sportage 1.6 Turbo',
    description: '1.6 L turbo, jasur dizayn',
    price: 405000000,
    stock: 6,
    image: 'kia-sportage-1-6-turbo.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Hyundai Tucson 2.0',
    description: 'Zamonaviy dizayn, boy komplektatsiya',
    price: 395000000,
    stock: 7,
    image: 'hyundai-tucson-2-0.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Chevrolet Equinox 1.5 Turbo',
    description: 'Amerika krossoveri, keng salon',
    price: 375000000,
    stock: 5,
    image: 'chevrolet-equinox-1-5-turbo.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Kia Seltos 1.6',
    description: 'Ixcham krossover, yoshlar tanlovi',
    price: 315000000,
    stock: 8,
    image: 'kia-seltos-1-6.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Chevrolet Captiva 1.5 Turbo',
    description: '7 o‘rinli, keng oilaviy krossover',
    price: 295000000,
    stock: 9,
    image: 'chevrolet-captiva-1-5-turbo.jpg',
    category: 'Krossover va SUV',
  },
  {
    name: 'Chevrolet Tracker 1.2 Turbo',
    description: '1.2 L turbo, shahar krossoveri',
    price: 245000000,
    stock: 18,
    image: 'chevrolet-tracker-1-2-turbo.jpg',
    category: 'Krossover va SUV',
  },
  // ── Xetchbek ────────────────────────────────────────────────
  {
    name: 'Mazda 3 2.0',
    description: 'Chiroyli dizayn, premium salon',
    price: 295000000,
    stock: 4,
    image: 'mazda-3-2-0.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Volkswagen Golf 1.4 TSI',
    description: 'Xetchbeklar etaloni',
    price: 285000000,
    stock: 4,
    image: 'volkswagen-golf-1-4-tsi.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Ford Focus 1.5 EcoBoost',
    description: 'Dinamik boshqaruv, sport his',
    price: 255000000,
    stock: 3,
    image: 'ford-focus-1-5-ecoboost.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Volkswagen Polo 1.6',
    description: 'Ixcham, tejamkor, sifatli',
    price: 235000000,
    stock: 6,
    image: 'volkswagen-polo-1-6.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Toyota Yaris 1.5',
    description: 'Shahar uchun ideal, juda tejamkor',
    price: 225000000,
    stock: 7,
    image: 'toyota-yaris-1-5.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Peugeot 208 1.2',
    description: 'Fransuz dizayni, i-Cockpit paneli',
    price: 215000000,
    stock: 4,
    image: 'peugeot-208-1-2.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Renault Clio 1.0 TCe',
    description: 'Yevropa bozorining sardori',
    price: 205000000,
    stock: 5,
    image: 'renault-clio-1-0-tce.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Chevrolet Onix 1.0 Turbo',
    description: '1.0 L turbo, zamonaviy multimedia',
    price: 195000000,
    stock: 12,
    image: 'chevrolet-onix-1-0-turbo.jpg',
    category: 'Xetchbek',
  },
  {
    name: 'Chevrolet Spark 1.0',
    description: '1.0 L, shahar uchun eng ixcham',
    price: 118000000,
    stock: 21,
    image: 'chevrolet-spark-1-0.jpg',
    category: 'Xetchbek',
  },
  // ── Elektromobil ────────────────────────────────────────────
  {
    name: 'Porsche Taycan 4S',
    description: 'Sport elektromobil, 800V tizim',
    price: 1450000000,
    stock: 1,
    image: 'porsche-taycan-4s.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Tesla Model S Plaid',
    description: '1020 ot kuchi, 0-100 km/soat 2.1 s',
    price: 1250000000,
    stock: 1,
    image: 'tesla-model-s-plaid.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Tesla Model X Long Range',
    description: 'Falcon eshiklar, 7 o‘rin',
    price: 1180000000,
    stock: 1,
    image: 'tesla-model-x-long-range.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Tesla Cybertruck AWD',
    description: 'Zanglamaydigan po‘lat korpus',
    price: 1050000000,
    stock: 0,
    image: 'tesla-cybertruck-awd.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Tesla Model Y Performance',
    description: 'Krossover, 514 km masofa, AWD',
    price: 720000000,
    stock: 4,
    image: 'tesla-model-y-performance.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Tesla Model 3 Long Range',
    description: '629 km masofa, 0-100 km/soat 4.4 s',
    price: 615000000,
    stock: 6,
    image: 'tesla-model-3-long-range.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Kia EV6 GT-Line',
    description: '528 km masofa, sport dizayn',
    price: 545000000,
    stock: 3,
    image: 'kia-ev6-gt-line.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Hyundai Ioniq 5',
    description: '800V arxitektura, 18 daqiqada 80%',
    price: 520000000,
    stock: 4,
    image: 'hyundai-ioniq-5.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Volkswagen ID.4 Pro',
    description: 'Nemis elektro krossoveri',
    price: 480000000,
    stock: 3,
    image: 'volkswagen-id-4-pro.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'BYD Seal AWD',
    description: 'Sport elektro sedan, Blade batareya',
    price: 465000000,
    stock: 4,
    image: 'byd-seal-awd.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'BYD Han EV',
    description: 'Premium elektro sedan, 605 km',
    price: 445000000,
    stock: 5,
    image: 'byd-han-ev.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'BYD Song Plus EV',
    description: '505 km masofa, keng krossover',
    price: 385000000,
    stock: 9,
    image: 'byd-song-plus-ev.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Nissan Leaf 62 kWh',
    description: 'Dunyodagi birinchi ommaviy elektromobil',
    price: 295000000,
    stock: 5,
    image: 'nissan-leaf-62-kwh.jpg',
    category: 'Elektromobil',
  },
  {
    name: 'Chevrolet Bolt EUV',
    description: '417 km masofa, arzon elektromobil',
    price: 275000000,
    stock: 7,
    image: 'chevrolet-bolt-euv.jpg',
    category: 'Elektromobil',
  },
  // ── Sport avtomobil ─────────────────────────────────────────
  {
    name: 'Ferrari 488 GTB',
    description: '3.9 L V8 Turbo, 670 ot kuchi',
    price: 4850000000,
    stock: 0,
    image: 'ferrari-488-gtb.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Lamborghini Huracan EVO',
    description: '5.2 L V10, 640 ot kuchi',
    price: 4500000000,
    stock: 0,
    image: 'lamborghini-huracan-evo.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Audi R8 V10 Performance',
    description: '5.2 L V10, quattro, 620 ot kuchi',
    price: 2350000000,
    stock: 0,
    image: 'audi-r8-v10-performance.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Mercedes-AMG GT 63',
    description: '4.0 V8 Biturbo, 585 ot kuchi',
    price: 1950000000,
    stock: 1,
    image: 'mercedes-amg-gt-63.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Porsche 911 Carrera S',
    description: '3.0 L Twin-Turbo, 450 ot kuchi',
    price: 1850000000,
    stock: 1,
    image: 'porsche-911-carrera-s.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'BMW M3 Competition',
    description: '3.0 L, 510 ot kuchi, xForce',
    price: 1550000000,
    stock: 1,
    image: 'bmw-m3-competition.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Nissan GT-R R35',
    description: '3.8 V6 Twin-Turbo, «Godzilla»',
    price: 1450000000,
    stock: 1,
    image: 'nissan-gt-r-r35.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Chevrolet Corvette C8',
    description: '6.2 L V8 o‘rta joylashuv, 495 ot',
    price: 1350000000,
    stock: 1,
    image: 'chevrolet-corvette-c8.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Toyota GR Supra 3.0',
    description: '3.0 L, orqa uzatma, 382 ot kuchi',
    price: 920000000,
    stock: 1,
    image: 'toyota-gr-supra-3-0.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Ford Mustang GT 5.0',
    description: '5.0 L V8 Coyote, 450 ot kuchi',
    price: 850000000,
    stock: 2,
    image: 'ford-mustang-gt-5-0.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Dodge Challenger R/T',
    description: '5.7 L HEMI V8, muskul avtomobil',
    price: 790000000,
    stock: 2,
    image: 'dodge-challenger-r-t.jpg',
    category: 'Sport avtomobil',
  },
  {
    name: 'Subaru WRX STI',
    description: 'Boxer dvigatel, ralli merosi',
    price: 620000000,
    stock: 2,
    image: 'subaru-wrx-sti.jpg',
    category: 'Sport avtomobil',
  },
  // ── Lyuks va premium ────────────────────────────────────────
  {
    name: 'Mercedes-Benz G63 AMG',
    description: '4.0 V8 Biturbo, afsonaviy Gelandewagen',
    price: 3150000000,
    stock: 1,
    image: 'mercedes-benz-g63-amg.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Range Rover Vogue',
    description: 'Britaniya lyuksi, yo‘lsizlik shohi',
    price: 2650000000,
    stock: 1,
    image: 'range-rover-vogue.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Lexus LX 600',
    description: '3.5 V6 Twin-Turbo, flagman SUV',
    price: 2450000000,
    stock: 1,
    image: 'lexus-lx-600.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Mercedes-Benz S500',
    description: 'Dunyodagi eng mashhur lyuks sedan',
    price: 2250000000,
    stock: 1,
    image: 'mercedes-benz-s500.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Porsche Cayenne S',
    description: 'Sport krossover, 474 ot kuchi',
    price: 1850000000,
    stock: 1,
    image: 'porsche-cayenne-s.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'BMW 740i',
    description: 'Flagman sedan, maksimal komfort',
    price: 1750000000,
    stock: 1,
    image: 'bmw-740i.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'BMW X7 xDrive40i',
    description: '7 o‘rinli flagman SUV',
    price: 1650000000,
    stock: 1,
    image: 'bmw-x7-xdrive40i.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Mercedes-Benz GLE 450',
    description: 'Premium krossover, havo podveska',
    price: 1450000000,
    stock: 1,
    image: 'mercedes-benz-gle-450.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'BMW X5 xDrive40i',
    description: '3.0 L, premium krossover',
    price: 1350000000,
    stock: 2,
    image: 'bmw-x5-xdrive40i.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Audi Q7 55 TFSI',
    description: '7 o‘rin, quattro to‘liq uzatma',
    price: 1350000000,
    stock: 1,
    image: 'audi-q7-55-tfsi.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Lexus RX 350',
    description: 'Yapon lyuks krossoveri',
    price: 1150000000,
    stock: 2,
    image: 'lexus-rx-350.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Mercedes-Benz E300',
    description: 'Biznes klass etaloni',
    price: 1120000000,
    stock: 2,
    image: 'mercedes-benz-e300.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'BMW 530i xDrive',
    description: 'To‘liq uzatma, biznes klass',
    price: 1050000000,
    stock: 2,
    image: 'bmw-530i-xdrive.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Audi A6 45 TFSI',
    description: 'quattro, virtual kokpit',
    price: 950000000,
    stock: 2,
    image: 'audi-a6-45-tfsi.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'Mercedes-Benz C200',
    description: '1.5 L EQBoost, elegant sedan',
    price: 780000000,
    stock: 3,
    image: 'mercedes-benz-c200.jpg',
    category: 'Lyuks va premium',
  },
  {
    name: 'BMW 320i M Sport',
    description: '2.0 L turbo, sport sozlamalar',
    price: 720000000,
    stock: 3,
    image: 'bmw-320i-m-sport.jpg',
    category: 'Lyuks va premium',
  },
  // ── Minivan ─────────────────────────────────────────────────
  {
    name: 'Toyota Alphard 2.5',
    description: 'VIP minivan, biznes salon',
    price: 980000000,
    stock: 2,
    image: 'toyota-alphard-2-5.jpg',
    category: 'Minivan',
  },
  {
    name: 'Honda Odyssey 3.5',
    description: '8 o‘rin, oilaviy sayohat uchun',
    price: 620000000,
    stock: 2,
    image: 'honda-odyssey-3-5.jpg',
    category: 'Minivan',
  },
  {
    name: 'Kia Carnival 3.5',
    description: '11 o‘rinli variant ham mavjud',
    price: 585000000,
    stock: 3,
    image: 'kia-carnival-3-5.jpg',
    category: 'Minivan',
  },
  {
    name: 'Chevrolet Orlando 1.5 Turbo',
    description: '7 o‘rin, ixcham minivan',
    price: 310000000,
    stock: 6,
    image: 'chevrolet-orlando-1-5-turbo.jpg',
    category: 'Minivan',
  },
  // ── Pikap va yuk ────────────────────────────────────────────
  {
    name: 'Ford F-150 Lariat',
    description: 'Amerikaning eng ko‘p sotilgan pikapi',
    price: 950000000,
    stock: 2,
    image: 'ford-f-150-lariat.jpg',
    category: 'Pikap va yuk',
  },
  {
    name: 'RAM 1500 Big Horn',
    description: 'Havo podveska, lyuks pikap',
    price: 920000000,
    stock: 1,
    image: 'ram-1500-big-horn.jpg',
    category: 'Pikap va yuk',
  },
  {
    name: 'Chevrolet Silverado 1500',
    description: '5.3 V8, kuchli tortish qobiliyati',
    price: 890000000,
    stock: 2,
    image: 'chevrolet-silverado-1500.jpg',
    category: 'Pikap va yuk',
  },
  {
    name: 'Toyota Tacoma 3.5 V6',
    description: 'O‘rta o‘lchamli pikap',
    price: 720000000,
    stock: 2,
    image: 'toyota-tacoma-3-5-v6.jpg',
    category: 'Pikap va yuk',
  },
  {
    name: 'Toyota Hilux 2.8 Diesel',
    description: '2.8 L dizel, buzilmas ishonchlilik',
    price: 680000000,
    stock: 4,
    image: 'toyota-hilux-2-8-diesel.jpg',
    category: 'Pikap va yuk',
  },
  {
    name: 'Nissan Navara 2.3 Diesel',
    description: '2.3 L dizel, ish uchun',
    price: 560000000,
    stock: 3,
    image: 'nissan-navara-2-3-diesel.jpg',
    category: 'Pikap va yuk',
  },
  {
    name: 'Chevrolet Damas 0.8',
    description: 'Kichik biznes uchun eng arzon yuk mashinasi',
    price: 98000000,
    stock: 14,
    image: 'chevrolet-damas-0-8.jpg',
    category: 'Pikap va yuk',
  },
  {
    name: 'Chevrolet Labo 0.8',
    description: 'Ochiq kuzovli mini yuk mashinasi',
    price: 92000000,
    stock: 9,
    image: 'chevrolet-labo-0-8.jpg',
    category: 'Pikap va yuk',
  },
];
