/**
 * Swagger'dagi «Pickup Points» bo'limining tepasida turadigan QO'LLANMA.
 *
 * Bu yerda ATAYLAB kam kod bor. Salon endpointlari kategoriya va avtomobil
 * endpointlari bilan bir xil ishlaydi — bolalar ularni allaqachon yozgan,
 * qayta ko'rsatish shart emas. Kod faqat YANGI ikkita narsa uchun berilgan:
 * brauzerdan joylashuvni olish va xaritada ochish.
 *
 * Matnni qator-qator yozib `join('\n')` qilamiz: shunda kod bloklarining
 * ``` belgilarini ekranlash (escape) kerak bo'lmaydi.
 */

export const PICKUP_POINTS_TAG = '6. Pickup Points — tarqatuvchi salonlar';

export const PICKUP_POINTS_GUIDE = [
  '**Tarqatuvchi salon** — xaridor avtomobilni borib oladigan joy. Har bir avtomobil',
  'bitta salonda turadi; salon esa o‘nlab avtomobilni saqlaydi.',
  '',
  '---',
  '',
  '## 1. Kategoriya va salon — farqi nimada?',
  '',
  'Ikkalasi ham avtomobilga bog‘lanadi, lekin butunlay boshqa savolga javob beradi:',
  '',
  '| | Kategoriya | Salon (pickup point) |',
  '|---|---|---|',
  '| Savol | **Qanaqa** avtomobil? | **Qayerda** turibdi? |',
  '| Misol | Sedan, Krossover | Chilonzor, Samarqand |',
  '| Majburiymi | **Ha** — `categoryId` shart | **Yo‘q** — `pickupPointId` ixtiyoriy |',
  '| Nofaol qilinsa | avtomobillar ham nofaol bo‘ladi | avtomobillar **sotuvda qoladi** |',
  '',
  'Oxirgi qatorga e‘tibor bering. Kategoriya nofaol qilinsa, undagi avtomobillar ham',
  'sotuvdan chiqadi — chunki kategoriya avtomobilning **o‘z xususiyati**. Salon esa',
  'shunchaki turgan **joyi**: salon ta‘mirga yopilsa ham avtomobil yo‘qolib qolmaydi,',
  'uni boshqa salonga ko‘chirsa bo‘ladi.',
  '',
  '---',
  '',
  '## 2. Endpointlar kategoriyanikiga o‘xshaydi',
  '',
  'Pastdagi 9 ta endpointning 6 tasi siz allaqachon yozgan kategoriya endpointlari',
  'bilan **bir xil ishlaydi**: qo‘shish, ro‘yxat, bittasini ko‘rish, PUT, PATCH,',
  'faol/nofaol qilish, o‘chirish. Frontend kodi ham o‘sha-o‘sha — faqat manzil',
  '`/api/categories` o‘rniga `/api/pickup-points` bo‘ladi.',
  '',
  'Qolgan 3 tasi yangi:',
  '',
  '| Endpoint | Nima qiladi |',
  '|---|---|',
  '| `GET /pickup-points/{id}/products` | shu salondagi avtomobillar |',
  '| `GET /pickup-points/nearby` | eng yaqin salonlar (pastda) |',
  '| `GET /pickup-points/cities` | salon bor shaharlar — joylashuv aniqlanmaganda |',
  '| `GET /products?pickupPointId=3` | avtomobillar ro‘yxatini salon bo‘yicha filtrlash |',
  '| `POST /pickup-points/{id}/video` | salonga tanishtiruv videosi (pastda) |',
  '| `DELETE /pickup-points/{id}/video` | videoni o‘chirish |',
  '',
  'Oxirgi ikkitasi bir xil natija beradi. Qaysi birini tanlash kerak? **Salon sahifasi**',
  'ochilgan bo‘lsa — `/pickup-points/{id}/products`. **Avtomobillar sahifasida filtr**',
  'qo‘yayotgan bo‘lsangiz — `/products?pickupPointId=`, chunki uni boshqa filtrlar',
  '(narx, qidiruv, saralash) bilan birga ishlatsa bo‘ladi.',
  '',
  'Javobda ikkita **hisoblangan** maydon bor — ular bazada saqlanmaydi, server javob',
  'berayotganda hisoblaydi: `productsCount` (nechta avtomobil) va `isOpenNow`',
  '(hozir ochiqmi, Toshkent vaqti bilan).',
  '',
  '---',
  '',
  '## 3. Avtomobilni salonga biriktirish',
  '',
  'Avtomobil qo‘shayotganda `pickupPointId` ni qo‘shsangiz — avtomobil o‘sha salonda',
  'turadi. **Yubormasangiz ham bo‘ladi**: avtomobil hali yo‘lda bo‘lishi va hech qaysi',
  'salonda turmasligi mumkin.',
  '',
  'Keyin uni `PATCH /api/products/{id}` orqali boshqa salonga ko‘chirasiz',
  '(`{ "pickupPointId": 3 }`) yoki salondan butunlay chiqarasiz',
  '(`{ "pickupPointId": null }`).',
  '',
  '> **`null` haqida.** `pickupPointId` — bu loyihada `null` yuborish mumkin bo‘lgan',
  '> kam sonli maydonlardan biri, chunki «hech qaysi salonda emas» degan holat',
  '> haqiqatan ham bor. Boshqa maydonlarga (`name`, `price`, `categoryId`...) `null`',
  '> yuborsangiz xato qaytadi — o‘zgartirmoqchi bo‘lmasangiz, ularni **yubormang**.',
  '',
  '---',
  '',
  '## 4. Eng yaqin salon — brauzerdan joylashuvni olish',
  '',
  'Backend: **GET /api/pickup-points/nearby?lat=&lng=**',
  '',
  'Bu yerda yangi narsa bor: `lat` va `lng` ni **brauzerning o‘zi** beradi. Sizdan',
  'foydalanuvchi manzilini so‘rash shart emas — telefon yoki noutbuk o‘zi biladi',
  '(ruxsat so‘raydi):',
  '',
  '```js',
  'navigator.geolocation.getCurrentPosition(async (joylashuv) => {',
  '  const lat = joylashuv.coords.latitude;',
  '  const lng = joylashuv.coords.longitude;',
  '',
  '  const javob = await fetch(',
  '    `http://localhost:3000/api/pickup-points/nearby?lat=${lat}&lng=${lng}&radiusKm=25`,',
  '    { headers: { Authorization: "Bearer " + localStorage.getItem("token") } },',
  '  );',
  '',
  '  const natija = await javob.json();',
  '',
  '  // data — massiv, eng yaqinidan boshlab saralangan',
  '  for (const salon of natija.data) {',
  '    console.log(salon.name, salon.distanceKm + " km");',
  '  }',
  '}, (xato) => {',
  '  // Foydalanuvchi ruxsat bermasa shu yerga tushamiz — pastdagi zaxira yo‘lga o‘tamiz',
  '  console.log("Joylashuv olinmadi:", xato.message);',
  '  shaharniSora();',
  '});',
  '```',
  '',
  'Ikkinchi funksiyani (`xato`) tashlab ketmang: foydalanuvchi «ruxsat bermayman»',
  'desa yoki brauzer joylashuvni topolmasa, birinchi funksiya **umuman**',
  'chaqirilmaydi. O‘shanda sahifa bo‘m-bo‘sh qolib ketmasligi kerak.',
  '',
  'Koordinatasi yozilmagan salon bu ro‘yxatga **tushmaydi** — masofasini hisoblab',
  'bo‘lmaydi. Shuning uchun salon qo‘shayotganda `latitude` va `longitude` ni ham',
  'yozib qo‘ying.',
  '',
  '---',
  '',
  '## 5. Joylashuv aniqlanmasa — shaharni so‘rash',
  '',
  'Backend: **GET /api/pickup-points/cities**',
  '',
  'Joylashuv har doim ham qo‘lga kirmaydi: foydalanuvchi ruxsat bermaydi, qurilmada',
  'GPS yo‘q, xona ichida signal yetmaydi yoki sahifa HTTPS emas. Bunday holatda',
  '**foydalanuvchidan so‘rash** kerak — sahifa ishlamay qolmasin.',
  '',
  'Bu endpoint salon bor shaharlarni, har birida nechta ochiq salon borligini va',
  'shaharning taxminiy markazini qaytaradi:',
  '',
  '```js',
  'async function shaharniSora() {',
  '  const javob = await fetch("http://localhost:3000/api/pickup-points/cities", {',
  '    headers: { Authorization: "Bearer " + localStorage.getItem("token") },',
  '  });',
  '',
  '  const natija = await javob.json();',
  '',
  '  // Masalan: [{ city: "Toshkent", pickupPointsCount: 3, latitude: 41.28, longitude: 69.24 }]',
  '  for (const shahar of natija.data) {',
  '    select.innerHTML += `<option value="${shahar.city}">',
  '      ${shahar.city} (${shahar.pickupPointsCount} ta salon)</option>`;',
  '  }',
  '}',
  '```',
  '',
  'Foydalanuvchi shaharni tanlagach ikki yo‘l bor:',
  '',
  '1. `GET /pickup-points?city=Toshkent` — o‘sha shahardagi salonlar',
  '2. Yoki shahar markazining `latitude`/`longitude` sini `/nearby` ga yuborasiz —',
  '   shunda ro‘yxat masofasi bilan, eng yaqinidan boshlab keladi',
  '',
  'Ikkinchisi yaxshiroq: foydalanuvchi joylashuvni bermagan bo‘lsa ham, u kamida',
  'shahar markaziga qarab tartiblangan ro‘yxatni ko‘radi. Hech qanday xarita xizmati',
  'yoki API kaliti kerak emas.',
  '',
  '---',
  '',
  '## 6. Xaritada ochish',
  '',
  'Koordinata bor bo‘lsa, hech qanday xarita kutubxonasisiz havola yasash mumkin —',
  'bosilganda Google Maps o‘sha nuqtani ochadi:',
  '',
  '```js',
  'function xaritaHavolasi(salon) {',
  '  // Koordinata yo‘q bo‘lsa havola ham bo‘lmaydi —',
  '  // aks holda "undefined,undefined" degan buzuq havola chiqadi',
  '  if (salon.latitude === null || salon.longitude === null) return null;',
  '',
  '  return `https://www.google.com/maps?q=${salon.latitude},${salon.longitude}`;',
  '}',
  '```',
  '',
  '---',
  '',
  '## 7. Salonga video yuklash',
  '',
  'Backend: **POST /api/pickup-points/{id}/video**',
  '',
  'Bu yerda hamma narsa boshqacha: JSON emas, **fayl** yuboriladi.',
  '',
  '| | |',
  '|---|---|',
  '| Formatlar | `mp4`, `mov`, `webm` |',
  '| Hajmi | **50 MB** gacha |',
  '| Uzunligi | **30 soniya**. Uzunroq bo‘lsa server o‘zi kesadi |',
  '| Nechta | **Har salonda bitta.** Yangisi eskisini almashtiradi |',
  '',
  '**Videoni oldindan siqish shart emas** — server uni o‘zi 480p ga keltiradi.',
  'Telefondagi 21 MB lik video shu yerdan **0.9 MB** bo‘lib chiqadi.',
  '',
  '### Yuborish — `FormData` bilan',
  '',
  '```js',
  'const forma = new FormData();',
  'forma.append("video", input.files[0]);   // maydon nomi aynan "video"',
  '',
  'const javob = await fetch(`http://localhost:3000/api/pickup-points/${id}/video`, {',
  '  method: "POST",',
  '  // DIQQAT: Content-Type ni O‘ZINGIZ YOZMANG.',
  '  // Brauzer uni chegara belgisi bilan birga o‘zi qo‘yadi:',
  '  //   multipart/form-data; boundary=----WebKitFormBoundary...',
  '  // Qo‘lda yozsangiz chegara tushib qoladi va server faylni topa olmaydi.',
  '  headers: { Authorization: "Bearer " + localStorage.getItem("token") },',
  '  body: forma,',
  '});',
  '',
  'const natija = await javob.json();',
  'console.log(natija.data.videoUrl);',
  '```',
  '',
  '### Progress bar — `fetch` buni QILA OLMAYDI',
  '',
  'Video 20 soniya yuklanishi mumkin. Foydalanuvchi nima bo‘layotganini ko‘rmasa,',
  'sahifa qotib qolgandek tuyuladi. Lekin `fetch` da yuklash jarayonini kuzatish',
  '**imkoni yo‘q** — buning uchun eski `XMLHttpRequest` kerak:',
  '',
  '```js',
  'function videoYukla(id, fayl, foizniKorsat) {',
  '  return new Promise((resolve, reject) => {',
  '    const forma = new FormData();',
  '    forma.append("video", fayl);',
  '',
  '    const xhr = new XMLHttpRequest();',
  '    xhr.open("POST", `http://localhost:3000/api/pickup-points/${id}/video`);',
  '    xhr.setRequestHeader("Authorization", "Bearer " + localStorage.getItem("token"));',
  '',
  '    // Yuklash jarayoni — aynan shu narsa fetch da yo‘q',
  '    xhr.upload.onprogress = (hodisa) => {',
  '      if (hodisa.lengthComputable) {',
  '        foizniKorsat(Math.round((hodisa.loaded / hodisa.total) * 100));',
  '      }',
  '    };',
  '',
  '    xhr.onload = () => {',
  '      const natija = JSON.parse(xhr.responseText);',
  '      xhr.status < 400 ? resolve(natija) : reject(new Error(natija.message));',
  '    };',
  '    xhr.onerror = () => reject(new Error("Tarmoq xatosi"));',
  '',
  '    xhr.send(forma);',
  '  });',
  '}',
  '```',
  '',
  '> **Muhim:** foiz **100 ga yetgach javob darhol kelmaydi.** 100% — bu «fayl',
  '> serverga yetib bordi» degani, ammo server endi uni siqadi (yana bir necha',
  '> soniya). Shuning uchun 100% dan keyin «siqilyapti...» deb yozib qo‘ying,',
  '> aks holda bola dastur qotib qoldi deb o‘ylaydi.',
  '',
  '### Ko‘rsatish',
  '',
  '```js',
  '// videoUrl tayyor havola — token kerak emas (rasmlar kabi)',
  '// controls — o‘ynatish tugmalari, preload="metadata" — butun video',
  '// oldindan yuklanmaydi, faqat davomiyligi o‘qiladi',
  'salon.videoUrl',
  '  ? `<video src="${salon.videoUrl}" controls preload="metadata" width="320"></video>`',
  '  : "<p>Bu salonda video yo‘q</p>";',
  '```',
  '',
  'Videoni o‘chirish: `DELETE /api/pickup-points/{id}/video`. Salonning o‘zi',
  'o‘chirilganda videosi ham avtomatik o‘chadi — alohida chaqirish shart emas.',
].join('\n');
